#!/bin/bash

read -p "
Enter 1 if generating for Userge-X bot.
Enter 2 for latest pyrogram.
*** DO NOT enter 2 if generating for Userge-X. ***

>>> " pyroV

if [[ $pyroV == 1 ]]; then
  echo -e "\nInstalling pyrogram 1.4.7"
  pip -q install pyrogram==1.4.7
  echo -e " -Done \n"
elif [[ $pyroV == 2 ]]; then
  echo -e "\nInstalling latest pyrogram"
  pip -q install -U pyrogram
  echo -e " - Done \n"
else
  echo -e "\nWrong Input, run \`bash gen\` again.

*** If this is your 1st time running script then you might need to run 
\`cd string\`
before running bash gen. ***"
  exit
fi

python gen.py
